### ISSUE TITLE
extend first part to match width

### ISSUE THREAD

**Issue by ioana-chiorean** [jsheroes/website#15]
There are some grey side parts visible.

<img width="273" alt="Screenshot 2022-10-27 at 21 37 51" src="https://user-images.githubusercontent.com/1391451/198382841-2faf1434-0e48-40fb-a419-dc00d1909155.png">

<img width="531" alt="Screenshot 2022-10-27 at 21 37 34" src="https://user-images.githubusercontent.com/1391451/198382852-bd0400ba-69c3-4b9d-8c0d-e525b0748a4a.png">

**Comment by alexnm** [comment]
Yes, need to re-export from figma and fix the positioning
