### ISSUE TITLE
<Cluj> vs <Cluj-Napoca>

### ISSUE THREAD

**Issue by ioana-chiorean** [jsheroes/website#16]
A bit of pickiness - If we use Cluj-Napoca in the first part, we should be consistent in the second part. Plus Cluj is the county, the city is CLuj-Napcoa :S 

"Looking forward to seeing you all back in Cluj, on the 18th and 19th of May 2023!"

**Comment by alexnm** [comment]
Wonder if we should stick to Cluj everywhere just as a form of protest for the communist absurdity of adding Napoca to the name :P

**Comment by ioana-chiorean** [comment]
Uh oh, some local spiciness.. I think u can decide as probably the most local of us :))

**Comment by alexnm** [comment]
haha :))

**Comment by alexnm** [comment]
On a more serious note, I think it's better to have the official name when used "officially", like in an address or a location, but to refer to it as `Cluj` in sentences, because of the familiarity of the name
