### ISSUE TITLE
Dusan Todorovic: Add guest-writer and article reference 

### ISSUE THREAD

**Issue by krckyboy** [jsheroes/website#164]
To whoever will be working on this blog, this is the [link](https://www.todorovic.dev/blog/unlocking-opportunities-why-conferences-matter) to the article and you are free to use any part of the text you wish.

**Comment by krckyboy** [comment]
Trying to push, yet I don't have authorization, so I'll drop code here:

```md
---
name: "Dušan Todorović"
title: "Guest Writer"
imgName: "guest-writers/dusan-todorovic.png"
links:
  {
    link: "https://www.todorovic.dev",
    linkedin: "https://www.linkedin.com/in/dusan-todorovic-krcky",
    github: "https://github.com/krckyboy"
  }
---

Dušan Todorović is a seasoned Software Engineer who shines in blending his technical know-how with strong leadership and interpersonal skills. He takes a holistic view of software engineering, seeing the value in soft skills for pushing projects forward and building a great team atmosphere along with continuous learning. More at https://todorovic.dev
```

Image:

![dt](https://github.com/jsheroes/website/assets/11292329/d0e2e7e8-8821-4285-93a3-d1ab5593fe0b)

**Comment by alexnm** [comment]
Hey! thanks, I'll take it from here! Thank you for writing the article, we'll add a few paragraphs on our blog and link to your website for the entire article.

**Comment by alexnm** [comment]
Made a PR, here's how it would look on the website: https://website-git-draft-gifted-margulis-jsheroes.vercel.app/blog/unlocking-opportunities-why-conferences-matter

**Comment by krckyboy** [comment]
> Made a PR, here's how it would look on the website: https://website-git-draft-gifted-margulis-jsheroes.vercel.app/blog/unlocking-opportunities-why-conferences-matter

Perfect! All good from what I see. Feel free to merge this! 👍
