### ISSUE TITLE
Stars get in the way of white text

### ISSUE THREAD

**Issue by jeremenichelli** [jsheroes/website#29]
I think we need to be careful with these things, maybe clear the image in the center so stars don't pollute white text hurting readability.

<img width="465" alt="Screenshot 2022-11-01 at 09 46 05" src="https://user-images.githubusercontent.com/3856481/199194746-6cd65d31-c25d-4098-bdc7-a2c215cdedf6.png">

**Comment by alexnm** [comment]
good catch, I stopped seeing these small details after checking the website so often lately :D
