### ISSUE TITLE
Add paragraph to event description

### ISSUE THREAD

**Issue by alexnm** [jsheroes/website#62]
There's a section on the website where we describe the idea of the "open source event". Add this paragraph before the existing content

<img width="909" alt="image" src="https://user-images.githubusercontent.com/9945366/213293023-841ae7dc-2c9a-46db-bca7-bd939f1fc2d0.png">

"JSHeroes is a non-profit community-organized conference, held every year in Cluj, Romania. Our goal is to bring together JS and Web/Frontend development enthusiasts from all over the world for a two day event with: great talks, amazing networking and tons of fun. You bring your ideas and desire to learn, we provide the relaxed atmosphere and the good vibes."

**Comment by DavidRod1865** [comment]
Hello Alex! I wish to work on this issue! 
Should this paragraph be the 1st paragraph?

**Comment by alexnm** [comment]
@DavidRod1865 yes, this should be the first paragraph, feel free to pick it is up
